### ISSUE TITLE
Correct ID for thunderbird?

### ISSUE THREAD

**Issue by probonopd** [hughsie/fedora-appstream#165]
On Ubuntu, I get:
```
me@host:~$ appstreamcli dump thunderbird.desktop
<?xml version="1.0" encoding="utf-8"?>
<component type="desktop">
  <id>thunderbird.desktop</id>
  <name>Thunderbird Mail</name>
```

So the ID is `thunderbird.desktop` in Ubuntu but `mozilla-thunderbird.desktop` in this repository. Isn't the whole point of the ID to refer to the same application under the same ID?

**Comment by probonopd** [comment]
Possibly related to https://bugzilla.mozilla.org/show_bug.cgi?id=1071065 since upstream should give the official ID, correct?

**Comment by hughsie** [comment]
The extra AppData files in fedora-appstream are not actually used anymore (although the extra-appstream content still is) -- the files are removed once upstream is shipping an appdata file, rather than letting packagers reference these files in rpm spec files. The stance we have now is that apps need AppData upstream, or in the distro packages directly.
